inherited ListadoFrame: TListadoFrame
  Width = 882
  Height = 676
  ExplicitWidth = 882
  ExplicitHeight = 676
  object panelbusquedavanzada: TPanel [0]
    AlignWithMargins = True
    Left = 0
    Top = 5
    Width = 882
    Height = 46
    Margins.Left = 0
    Margins.Top = 5
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alTop
    BevelOuter = bvNone
    Caption = 'paneltop'
    ParentColor = True
    ShowCaption = False
    TabOrder = 0
    StyleName = 'Windows'
    object buscaedit: TEdit
      AlignWithMargins = True
      Left = 159
      Top = 10
      Width = 406
      Height = 26
      Margins.Left = 10
      Margins.Top = 10
      Margins.Bottom = 10
      Align = alLeft
      TabOrder = 0
      TextHint = 'Texto a buscar'
      ExplicitHeight = 23
    end
    object botonbuscar: TButton
      AlignWithMargins = True
      Left = 578
      Top = 3
      Width = 40
      Height = 40
      Margins.Left = 10
      Action = dmActions.actSearch
      Align = alLeft
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      StyleName = 'Windows'
    end
    object botonborrarfiltro: TButton
      AlignWithMargins = True
      Left = 626
      Top = 3
      Width = 40
      Height = 40
      Margins.Left = 5
      Action = dmActions.actClearFilter
      Align = alLeft
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 2
      StyleName = 'Windows'
    end
    object botonfiltrar: TButton
      AlignWithMargins = True
      Left = 674
      Top = 3
      Width = 40
      Height = 40
      Margins.Left = 5
      Action = dmActions.actFilter
      Align = alLeft
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 3
      StyleName = 'Windows'
    end
    object Botonnuevo: TButton
      AlignWithMargins = True
      Left = 10
      Top = 3
      Width = 40
      Height = 40
      Margins.Left = 10
      Action = dmActions.actAdd
      Align = alLeft
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 4
      StyleName = 'Windows'
    end
    object Botoneditar: TButton
      AlignWithMargins = True
      Left = 58
      Top = 3
      Width = 40
      Height = 40
      Margins.Left = 5
      Action = dmActions.actEdit
      Align = alLeft
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 5
      StyleName = 'Windows'
    end
    object botonsalir: TButton
      AlignWithMargins = True
      Left = 832
      Top = 3
      Width = 40
      Height = 40
      Margins.Left = 5
      Margins.Right = 10
      Action = dmActions.actClose
      Align = alRight
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      TabOrder = 6
      StyleName = 'Windows'
    end
    object btnborrar: TButton
      AlignWithMargins = True
      Left = 106
      Top = 3
      Width = 40
      Height = 40
      Margins.Left = 5
      Action = dmActions.actDelete
      Align = alLeft
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 7
      StyleName = 'Windows'
    end
  end
  object Panelfiltros: TPanel [1]
    AlignWithMargins = True
    Left = 0
    Top = 51
    Width = 882
    Height = 7
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alTop
    BevelOuter = bvNone
    Caption = 'paneltop'
    Color = 16382457
    ParentBackground = False
    ShowCaption = False
    TabOrder = 1
    Visible = False
    StyleName = 'Windows'
  end
  object DBGridListado: TDBGrid [2]
    AlignWithMargins = True
    Left = 61
    Top = 68
    Width = 811
    Height = 598
    Margins.Left = 10
    Margins.Top = 10
    Margins.Right = 10
    Margins.Bottom = 10
    Align = alClient
    DataSource = DataSource
    DrawingStyle = gdsGradient
    FixedColor = 15849882
    GradientEndColor = 16382457
    GradientStartColor = 16382457
    Options = [dgTitles, dgIndicator, dgColumnResize, dgTabs, dgRowSelect, dgConfirmDelete, dgCancelOnExit, dgTitleClick, dgTitleHotTrack]
    ReadOnly = True
    TabOrder = 2
    TitleFont.Charset = DEFAULT_CHARSET
    TitleFont.Color = clWindowText
    TitleFont.Height = -12
    TitleFont.Name = 'Segoe UI'
    TitleFont.Style = []
    OnDrawColumnCell = DBGridListadoDrawColumnCell
  end
  object Menulateral: TPanel [3]
    AlignWithMargins = True
    Left = 5
    Top = 68
    Width = 46
    Height = 608
    Margins.Left = 5
    Margins.Top = 10
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alLeft
    BevelOuter = bvNone
    Caption = 'paneltop'
    ParentColor = True
    ShowCaption = False
    TabOrder = 3
    Visible = False
    StyleName = 'Windows'
    object Botonnuevo2: TButton
      AlignWithMargins = True
      Left = 0
      Top = 0
      Width = 46
      Height = 40
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Action = dmActions.actAdd
      Align = alTop
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 0
      StyleName = 'Windows'
    end
    object Botoneditar2: TButton
      AlignWithMargins = True
      Left = 0
      Top = 40
      Width = 46
      Height = 40
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Action = dmActions.actEdit
      Align = alTop
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      StyleName = 'Windows'
    end
    object btnborrar2: TButton
      AlignWithMargins = True
      Left = 0
      Top = 80
      Width = 46
      Height = 40
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Action = dmActions.actDelete
      Align = alTop
      ImageAlignment = iaCenter
      Images = dmImages.VirtualImageList1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 2
      StyleName = 'Windows'
    end
  end
  inherited FDQuery: TFDQuery
    Connection = DataModuleConnection.FDConnectionCompany
    Left = 472
    Top = 24
  end
  inherited DataSource: TDataSource
    Left = 408
    Top = 24
  end
end
